Repository RubenJ01/rewrite, pull requests merged in 2019-04, with the labels that each got.

#15 added the reddit meme command
  Pipfile.lock
  bot.py
  cogs/reddit.py
Labels: command

#17 added new help message and removed old one
  bot.py
  cogs/specialcog.py
Labels: command, enhancement

#30 Various changes, such as Diceroll changes and requested changes
  .gitignore
  cogs/reddit.py
  cogs/rollingcog.py
  cogs/specialcog.py
  utils/helpers.py
Labels: enhancement
